# Generated by Django 3.2.3 on 2022-03-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbalism', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='drug',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='isDrug',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='nightOnly',
            field=models.BooleanField(default=0),
        ),
    ]
