# Generated by Django 3.2.3 on 2022-03-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbalism', '0003_auto_20220302_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='isDrug',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='nightOnly',
            field=models.BooleanField(default=False),
        ),
    ]
