# Generated by Django 3.2.3 on 2022-03-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbalism', '0004_auto_20220302_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='effect',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
