# Generated by Django 3.2.3 on 2022-03-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbalism', '0005_auto_20220302_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='magic',
            field=models.BooleanField(default=False),
        ),
    ]
