# Generated by Django 3.2.3 on 2022-03-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbalism', '0006_ingredient_magic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='isDrug',
            new_name='isMagic',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='magic',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='nightOnly',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='difficult',
            field=models.IntegerField(default=0),
        ),
    ]
