# Generated by Django 3.2.3 on 2022-03-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbalism', '0007_auto_20220302_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rarity', models.IntegerField(default=0)),
                ('effect', models.TextField(default='')),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='rarity',
            field=models.IntegerField(default=0),
        ),
    ]
