# Generated by Django 3.2.3 on 2022-03-10 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbalism', '0008_auto_20220310_1743'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poison',
            new_name='Potion',
        ),
    ]
