# Generated by Django 3.2.3 on 2022-03-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbalism', '0009_rename_poison_potion'),
    ]

    operations = [
        migrations.AddField(
            model_name='potion',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
